Refactor logging
open-telemetry/opentelemetry-dotnet-instrumentation pull request #2145
Opened 2023-02-02 11:28 UTC by dszmigielski

## Why

Fixes #

## What

## Tests

## Checklist

- [ ] `CHANGELOG.md` is updated.
- [ ] Documentation is updated.
- [ ] New features are covered by tests.

2023-02-02 12:22 UTC, RassK commented on src/OpenTelemetry.AutoInstrumentation/Configurations/Propagator.cs
> +    /// W3C Information Context propagator.
error in find & replace

2023-02-03 02:14 UTC, rajkumar-rangaraj requested changes
When `EventSource` is shared between different project, it will throw an error during initialization but may not crash the process. 

**Error:** An instance of EventSource with Guid already exists.

Please validate and confirm we are not throwing this error. If this error is thrown event source messages will not be emitted.

2023-02-07 15:45 UTC, pellared commented
> Extract base class for EventSource, and pass its implementation to the CustomLogger as parameter.

It seams reasonable. This is what I initially had in mind [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1983/files#r1072147421).

2023-02-09 02:15 UTC, rajkumar-rangaraj commented
> > Extract base class for EventSource, and pass its implementation to the CustomLogger as parameter.
> 
> It seams reasonable. This is what I initially had in mind [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1983/files#r1072147421).
> 
> @rajkumar-rangaraj any preferences?

I'm fine with option 1, was worried about missing event source in the current proposal.

2023-02-27 10:46 UTC, Kielek commented
@rajkumar-rangaraj, concept changed a bit.
With Robert we have decided to use same code twice. Just EventSourceName is different.

2023-02-27 10:46 UTC, Kielek approved these changes

2023-02-27 10:59 UTC, pellared approved these changes

2023-02-27 12:51 UTC, RassK approved these changes
Seems good for now but I think needs further refactoring - separating both sinks (file and event source).

2023-02-27 12:58 UTC, pellared commented
@rajkumar-rangaraj Can you please double-check please (even after it is merged)?

2023-02-27 12:59 UTC, merged